### ISSUE TITLE
Enhance Documentation 

### ISSUE THREAD

**Issue by B-Stefan** [DLR-SC/prov-db-connector#24]
Fix some missing code lines in examples and documentation  
- Fix missing imports in [Database-Adapaters.md](./docs/Database-Adapaters.md)
- Try the tutorial in Database-Adapaters.md, step by step

**Comment by Drake81** [comment]
Imports and Code in Database-Adapters.md fixed in #27 

Tutorial must be tested after merge in master due to pip.

**Comment by Drake81** [comment]
Tutorial fixed with 31fbc6f691501fc
Seems to be working.
