### ISSUE TITLE
Improve documentation of test case templates

### ISSUE THREAD

**Issue by Drake81** [DLR-SC/prov-db-connector#29]
- [x] Fix readthedocs.io building (acess to project is missing right now)   
- [x] Add doc strings with explanation of expected results to tests
- [x] Extend [Database-Adapaters.md](https://github.com/DLR-SC/prov-db-connector/blob/master/docs/Database-Adapaters.md) by a list which helps developers to implement test cases in correct order.

**Comment by B-Stefan** [comment]
I solved this by adding numbers to the test cases (so the order is clear) and I modified the [How-To-Test](https://github.com/DLR-SC/prov-db-connector/blob/documentation/docs/source/test_howto.rst) site. 

Also I added doc strings to the [test_baseadapter.py](https://github.com/DLR-SC/prov-db-connector/blob/documentation/provdbconnector/tests/db_adapters/test_baseadapter.py)

**Comment by B-Stefan** [comment]
I get an error during the build on http://prov-db-connector.readthedocs.io/  but I don't have access for the project.
