### ISSUE TITLE
Support Neo4j 4.x fabric for data sharding

### ISSUE THREAD

**Issue by onyame** [DLR-SC/prov-db-connector#86]
Add support for new Neo4j 4.x features for data sharding to split data over multiple Neo4j instances.
Implementation via Neo4j Fabric: https://neo4j.com/docs/operations-manual/current/fabric/introduction/

**Comment by B-Stefan** [comment]
@onyame  the Neoj4J Fabric is an advanced cluster feature. 
There should be no need to modify the lib to support this.
