### ISSUE TITLE
BaseConnector: Create tests for the base connector and implement the Neo4jConnector class 

### ISSUE THREAD

**Issue by B-Stefan** [DLR-SC/prov-db-connector#9]
Create a set of cases to test the implementation of the BaseConnector (Neo4j or Arango ... ) 
The following methods will be tested: 
- [create_document()](https://github.com/DLR-SC/prov-db-connector/blob/issue-%239-Create_tests_for_the_base_connector/provdbconnector/databases/neo4j/neo4jconnector.py#L42): string 
- [create_bundle(doc_id)](https://github.com/DLR-SC/prov-db-connector/blob/issue-%239-Create_tests_for_the_base_connector/provdbconnector/databases/neo4j/neo4jconnector.py#L54): string 
- [create_record(bundle_id, attributes: dict, metadata: dict, prov_record: ProvRecord)](https://github.com/DLR-SC/prov-db-connector/blob/issue-%239-Create_tests_for_the_base_connector/provdbconnector/databases/neo4j/neo4jconnector.py#L59): string 
- [create_relation(bundle_id,attributes: dict, metadata: dict , prov_relation: ProvRelation)](https://github.com/DLR-SC/prov-db-connector/blob/master/provdbconnector/databases/neo4j/neo4jadapter.py#L124): string 
- get_document(document_id: string): ProvDocument?
- get_bundle(bundle_id: string): ProvBundle? 
- get_record(record_id): ProvRecord?
- get_relation(relation_id): ProvRelation?
- delete_document(document_id): bool 
- delete_bundle(bundle_id): bool 
- delete_record(record_id): bool 
- delete_relation(relation_id): bool

**Comment by B-Stefan** [comment]
I already started this ;) see [this](https://github.com/DLR-SC/prov-db-connector/tree/issue-%239-Create_tests_for_the_base_connector) branch

**Comment by Drake81** [comment]
Okay :+1:

Just setup some more issues and I will work on them next week.
